base.url=https://www.saucedemo.com
username=standard_user
password=secret_sauce
browser=chrome
api.base.url=https://gorest.co.in/public/v2
gemini.key=AIzaSyAnS5nt0qJbEtxFwAOOj9pIpNuWRuJt1tA
report.path=reports/ExtentReport.html
screenshot.path=screenshots/